projects:
  foodbyhomebackend-staging:
    schemaPath: app/src/main/graphql/schema.json
    includes:
      - app/src/main/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: ''
        generatedFileName: ''
        docsFilePath: app/src/main/graphql/com/amazonaws/amplify/generated/graphql
        region: eu-central-1
        apiId: nhw57ya5yzeqjmbnfqrxolgybu
        maxDepth: 2
